language: python
sudo: false
before_script:
- pip install tox

# test script
script:  tox
notifications:
  on_success: change
  on_failure: always

matrix:
  include:
  - python: 2.6
    env: TOXENV=py26 REQUESTS_VERSION=""
  - python: 2.6
    env: TOXENV=py26 REQUESTS_VERSION="===2.2.1"
  - python: 2.6
    env: TOXENV=py26 REQUESTS_VERSION="===2.1.0"
  - python: 2.7
    env: TOXENV=py27 REQUESTS_VERSION=""
  - python: 2.7
    env: TOXENV=py27 REQUESTS_VERSION="===2.2.1"
  - python: 2.7
    env: TOXENV=py27 REQUESTS_VERSION="===2.1.0"
  - python: 3.2
    env: TOXENV=py32 REQUESTS_VERSION=""
  - python: 3.2
    env: TOXENV=py32 REQUESTS_VERSION="===2.2.1"
  - python: 3.2
    env: TOXENV=py32 REQUESTS_VERSION="===2.1.0"
  - python: 3.3
    env: TOXENV=py33 REQUESTS_VERSION=""
  - python: 3.3
    env: TOXENV=py33 REQUESTS_VERSION="===2.2.1"
  - python: 3.3
    env: TOXENV=py33 REQUESTS_VERSION="===2.1.0"
  - python: 3.4
    env: TOXENV=py34 REQUESTS_VERSION=""
  - python: 3.4
    env: TOXENV=py34 REQUESTS_VERSION="===2.2.1"
  - python: 3.4
    env: TOXENV=py34 REQUESTS_VERSION="===2.1.0"
  - python: 3.5
    env: TOXENV=py35 REQUESTS_VERSION=""
  - python: 3.5
    env: TOXENV=py35 REQUESTS_VERSION="===2.2.1"
  - python: 3.5
    env: TOXENV=py35 REQUESTS_VERSION="===2.1.0"
  - env: TOXENV=py27-flake8
  - env: TOXENV=py34-flake8
  - env: TOXENV=docstrings
  allow_failures:
  - env: TOXENV=docstrings
