language: python
before_script:
- pip install tox
- pip install -U requests"$REQUESTS_VERSION"

# test script
script:  tox -e ${TOX_ENV}
notifications:
  on_success: change
  on_failure: always

env:
  matrix:
  # With latest requests
  - TOX_ENV=py2 REQUESTS_VERSION=""
  - TOX_ENV=py2 REQUESTS_VERSION=""
  - TOX_ENV=py3 REQUESTS_VERSION=""
  - TOX_ENV=py3 REQUESTS_VERSION=""
  - TOX_ENV=py3 REQUESTS_VERSION=""
  - TOX_ENV=pyp REQUESTS_VERSION=""
  # With requests 2.2.1
  - TOX_ENV=py2 REQUESTS_VERSION="==2.2.1"
  - TOX_ENV=py2 REQUESTS_VERSION="==2.2.1"
  - TOX_ENV=py3 REQUESTS_VERSION="==2.2.1"
  - TOX_ENV=py3 REQUESTS_VERSION="==2.2.1"
  - TOX_ENV=py3 REQUESTS_VERSION="==2.2.1"
  - TOX_ENV=pyp REQUESTS_VERSION="==2.2.1"
  # With requets 2.1.0
  - TOX_ENV=py26 REQUESTS_VERSION="==2.1.0"
  - TOX_ENV=py27 REQUESTS_VERSION="==2.1.0"
  - TOX_ENV=py32 REQUESTS_VERSION="==2.1.0"
  - TOX_ENV=py33 REQUESTS_VERSION="==2.1.0"
  - TOX_ENV=py34 REQUESTS_VERSION="==2.1.0"
  - TOX_ENV=pypy REQUESTS_VERSION="==2.1.0"
  - TOX_ENV=py27-flake8
  - TOX_ENV=py34-flake8
  - TOX_ENV=docstrings

matrix:
  allow_failures:
  - env: TOX_ENV=docstrings
